---
- hosts: kubernetes_cluster
  become: yes
  gather_facts: yes
  tasks:
    - name: Update DNS in /etc/resolv.conf
      become: true
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 8.8.8.8"
        create: yes
        state: present

    - name: Update package lists and upgrade system
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install basic packages
      apt:
        name:
          - curl
          - net-tools
          - unzip
          - traceroute
          - sudo
          - vim
          - wget
          - build-essential
          - apt-transport-https 
          - ca-certificates 
          - software-properties-common
        state: present
        force_apt_get: yes