---
- hosts: kubernetes_cluster
  become: yes
  tasks:
    - name: Update packages and system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Create directory for apt keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download and add Kubernetes GPG key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository
      shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

    - name: Update packages and system
      apt:
        update_cache: yes
        
    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Disable swap
      command: swapoff -a

    - name: Remove swap from fstab
      lineinfile:
        path: /etc/fstab
        regexp: '\sswap\s'
        state: absent

    - name: Hold kubelet, kubeadm, and kubectl at the current version
      shell: apt-mark hold kubelet kubeadm kubectl

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Enable network parameters
      sysctl:
        name: "{{ item }}"
        value: 1
        state: present
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward

    - name: Add network settings to sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
        state: present
      loop:
        - 'net.bridge.bridge-nf-call-iptables=1'
        - 'net.ipv4.ip_forward=1'

    - name: Reload sysctl to apply new settings
      command: sysctl --system

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted

    - name: Restart kubelet
      systemd:
        name: kubelet
        state: restarted