---
- hosts: master-2,master-3
  become: yes
  tasks:
    - name: Copy join_command_masters.sh to master-2 and master-3
      copy:
        src: "/tmp/join_command_masters.sh"
        dest: "/home/{{ ansible_user }}/join_command_masters.sh"
        mode: '0777'

    - name: Join the control plane on master-2 and master-3
      command: bash /home/{{ ansible_user }}/join_command_masters.sh
      
    - name: Create directory .kube
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: '0755'

    - name: Copy kubeconfig 
      copy:
        src: /tmp/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        mode: '0644'